name: Oracle Database CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  oracle-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    services:
      oracle-db:
        image: gvenzl/oracle-free:slim
        env:
          ORACLE_RANDOM_PASSWORD: y
          APP_USER: ${{ secrets.DB_USER || 'test' }}
          APP_USER_PASSWORD: ${{ secrets.DB_PASSWORD || 'test' }}
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 15s
          --health-timeout 10s
          --health-retries 30
          --name oracle-db-container

    steps:
      - uses: actions/checkout@v3
      
      - name: Wait for Oracle
        run: |
          echo "Waiting for Oracle container to initialize..."
          sleep 30  # Tiempo extra para inicialización
          
      - uses: gvenzl/setup-oracle-sqlcl@v1
      
      - name: Test Connection
        run: |
          echo "SELECT 'CONEXIÓN EXITOSA: '||TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS') FROM dual;" \
          | sql ${{ secrets.DB_USER || 'test' }}/${{ secrets.DB_PASSWORD || 'test' }}@//localhost:1521/FREEPDB1