name: Oracle Database CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  database-service:
    runs-on: ubuntu-latest
    services:
      oracle:
        image: gvenzl/oracle-free:slim
        env:
          ORACLE_RANDOM_PASSWORD: y
          APP_USER: test 
          APP_USER_PASSWORD: test123  
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 15s
          --health-timeout 10s
          --health-retries 20
          --name oracle-service-container
    steps:
      - uses: actions/checkout@v3
      - uses: gvenzl/setup-oracle-sqlcl@v1
      - name: Test Basic Connection
        run: |
          echo "SELECT 'Servicio Oracle: Conexión exitosa con test/test123' FROM dual;" \
          | sql test/test123@//localhost:1521/FREEPDB1

  database-manual:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      
      - name: Verify Directory Structure
        run: |
          echo "=== Estructura Inicial ==="
          ls -R
          
      - name: Start Oracle Container
        run: |
          docker run -d --name oracle_manual \
          -p 1521:1521 \
          -e ORACLE_RANDOM_PASSWORD=y \
          -e APP_USER=test \
          -e APP_USER_PASSWORD=test123 \
          -v ./datamodel:/container-entrypoint-initdb.d \
          gvenzl/oracle-free:slim
          
          echo "Esperando inicialización de Oracle..."
          while ! docker logs oracle_manual 2>&1 | grep -q "DATABASE IS READY TO USE"; do
            sleep 5;
            echo "Todavía iniciando...";
          done
          
      - uses: gvenzl/setup-oracle-sqlcl@v1
      
      - name: Test Countries Query
        run: |
          echo "SELECT 'País: '||official_name||', Población: '||population \
          FROM countries WHERE name = 'Austria';" \
          | sql test/test123@//localhost:1521/FREEPDB1
          
      - name: Final Verification
        run: |
          echo "=== Estructura Final ==="
          ls -R
          docker ps -a

  database-action:
    needs: [database-service, database-manual]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare Directories
        run: |
          mkdir -p ${{ github.workspace }}/database-files
          echo "Directorios creados:"
          ls -l
          
      - uses: gvenzl/setup-oracle-free@v1
        with:
          app-user: test
          app-user-password: test123
          oracle-db-sid: FREEPDB1
          volume: ${{ github.workspace }}/database-files
          setup-scripts: ./datamodel
          health-check-retries: 25
          health-interval: 10s
          
      - uses: gvenzl/setup-oracle-sqlcl@v1
      
      - name: Comprehensive Test
        run: |
          echo "SELECT 'Configuración Action: Usuario=test, Contraseña=test123' FROM dual;
                SELECT 'Estado: '||status||', Versión: '||version FROM v\$instance;
                SELECT 'Total países: '||COUNT(*) FROM countries;" \
          | sql test/test123@//localhost:1521/FREEPDB1